- frontend/src/lib/hooks/filterUtils.ts
> Fix the ModeOptions Filter Value

- api/src/main/java/io/kafbat/ui/config/auth/LdapProperties.java
- api/src/main/resources/application-local.yml
- documentation/compose/ui-ldap.yaml
via https://github.com/provectus/kafka-ui/discussions/4422
> BE: Fix cyrillic in AD property name

- api/src/main/java/io/kafbat/ui/config/ReadOnlyModeFilter.java
> Allow smart filters endpoint in r/o mode

- pom.xml
Closes https://github.com/kafbat/kafka-ui/issues/307
Added an exclusion line in the pom.xml file for Sonar.
> Sonar: Configure to ignore e2e module code

- api/src/main/java/io/kafbat/ui/KafkaUiApplication.java
Disabling LDAP auto-configuration to prevent LDAP health check failed
Fixes #276
> Disabling LDAP auto-configuration to prevent LDAP health check failed

- frontend/src/components/Topics/Topic/Messages/Filters/Filters.tsx
> Bugfix: Cannot reuse filter display name

- api/src/main/java/io/kafbat/ui/service/rbac/AccessControlService.java
- frontend/src/components/ACLPage/List/List.tsx
> RBAC: Actions granted for cluster A are mistakenly available for cluster B

- frontend/src/components/Topics/shared/Form/TopicForm.tsx
Fixes #329
I changed the default value of the "Number of Partitions"-field to 1.
> UX: Topics: Set num of partitions to 1 by default

- README.md
- api/Dockerfile
Changes the base image used to ensure automatic inference, guaranteeing a correct base image for the built kafka-ui one.
Building the image with the updated base one the container boots successfully.
Closes: https://github.com/kafbat/kafka-ui/issues/376 
- Build and Run locally.
> Infra: Ensure image arch automatic inference

- frontend/src/components/Topics/shared/Form/TopicForm.tsx
- frontend/src/components/Topics/shared/Form/__tests__/TopicForm.spec.tsx
Fixes [#86](https://github.com/kafbat/kafka-ui/issues/86)
I renamed input label "max size on disk" to "Max partition size"
> FE: Rename "max size on disk" to "Max partition size"

- frontend/package.json
- frontend/pnpm-lock.yaml
Issue with spaces in route path in react-router-dom 6.4.3
https://github.com/remix-run/react-router/issues/9580
resolves#341
> FE: Clusters with spaces in names are not rendered

- api/src/main/java/io/kafbat/ui/service/rbac/extractor/RbacLdapAuthoritiesExtractor.java
Closes #390
I changed the way the LDAP groups of the user are collected. Instead of direct request to LDAP, I rely on the Spring LDAP class which has been designed to handle nested groups.
No
> BE: Auth: Support LDAP nested groups

- frontend/src/components/common/Select/Select.styled.ts
Increased `z-index` of select's dropdown element. Closes #394. Tested manually.
> FE: Fix white dot on the "Key Serde" dropdown

- api/src/main/java/io/kafbat/ui/emitter/OffsetsInfo.java
- api/src/main/java/io/kafbat/ui/emitter/RangePollingEmitter.java
> BE: Messages: Fix first offsets retrieval for compacted topic

- frontend/src/widgets/ClusterConfigForm/Sections/Authentication/Authentication.tsx
- frontend/src/widgets/ClusterConfigForm/Sections/KSQL.tsx
- frontend/src/widgets/ClusterConfigForm/Sections/KafkaCluster.tsx
- frontend/src/widgets/ClusterConfigForm/Sections/Metrics.tsx
- frontend/src/widgets/ClusterConfigForm/Sections/SchemaRegistry.tsx
- frontend/src/widgets/ClusterConfigForm/types.ts
- frontend/src/widgets/ClusterConfigForm/utils/transformFormDataToPayload.ts
I update the configure cluster sections to open and close properly. Prior to this change they would open, but not close consistently. I added a configOpen variable to manage this. Rather than passing undefined when the form is closed it now sets it to an {isActive: false}. Then the data is reset in transformFormDataToPayload based on that actual flag rather than null checking.
Check out [Contributing](https://github.com/kafbat/kafka-ui/blob/main/.github/CONTRIBUTING.md) and [Code of …
> FE: Wizard: Fix sections collapsing

- frontend/src/components/common/Switch/Switch.styled.ts
- frontend/src/components/common/Switch/Switch.tsx
> FE: Topics: Fix "Show internal topics" switch

- api/src/main/java/io/kafbat/ui/emitter/MessageFilters.java
- api/src/test/java/io/kafbat/ui/emitter/MessageFiltersTest.java
> BE: Messages: Add CEL extensions

- documentation/compose/DOCKER_COMPOSE.md
documentation
documentation
Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)
> Docs: Remove missing compose links

- contract/src/main/resources/swagger/kafbat-ui-api.yaml
- contract/src/main/resources/swagger/kafka-connect-api.yaml
> BE: KC: Fix connector listing with STOPPED state

- frontend/src/theme/theme.ts
> FE: UX: Fix header opacity

- api/src/main/java/io/kafbat/ui/controller/AccessController.java
- api/src/main/java/io/kafbat/ui/controller/KsqlController.java
- api/src/main/java/io/kafbat/ui/controller/TopicsController.java
- api/src/test/java/io/kafbat/ui/emitter/MessageFiltersTest.java
- contract/pom.xml
A little cleanup in the controller package.
> BE: Chore: Use dto builders in controller package

- api/src/main/java/io/kafbat/ui/config/auth/azure/AzureEntraLoginCallbackHandler.java
- api/src/main/java/io/kafbat/ui/config/auth/azure/AzureEntraOAuthBearerToken.java
> BE: Chore: Polishing

- api/pom.xml
- Tried to start contributing to this repo, but was stuck with a SIGSEV in the kafka-ui container (I'm on ARM64). Found the problematic dependency and excluded it, now everything builds as expected. Unit tests are still passing.
- [Link to discord convo](https://discord.com/channels/897805035122077716/1287174518946791535) for context.
- Ensure that the use of azure-identity in this repo doesn't depend on netty-tcnative-boringssl-static.
Check out [Contributing](https://github.com/kafbat/kafka-ui/blob/main/.github/ …
> Bugfix: SIGSEV in docker container on ARM64

- frontend/src/components/Schemas/Edit/Edit.tsx
- frontend/src/components/Topics/Topic/Edit/Edit.tsx
- frontend/src/lib/constants.ts
- frontend/src/lib/hooks/api/__tests__/schema.spec.ts
- frontend/src/lib/hooks/api/__tests__/topics.spec.ts
- frontend/src/lib/hooks/api/schemas.ts
- frontend/src/lib/hooks/api/topics.ts
Closes #348
I created a new constant QUERY_REFETCH_ON_WINDOW_FOCUS_OFF_OPTION that just has refetchOnWindowFocus false rather than
export const QUERY_REFETCH_OFF_OPTIONS = {
refetchOnMount: false,
refetchOnWindowFocus: false,
refetchIntervalInBackground: false,
};
I created this new constant because when all 3 options are provided, even when the Edit field is updated the UI will not reflect the changes until the page is refreshed. I added this constant to the two Edit components that fetch and place into editable fields.
**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build …
> FE: Fix refetching data on window focus

- api/src/main/java/io/kafbat/ui/service/ApplicationInfoService.java
- api/src/main/java/io/kafbat/ui/util/GithubReleaseInfo.java
- api/src/test/java/io/kafbat/ui/AbstractIntegrationTest.java
- api/src/test/java/io/kafbat/ui/service/ApplicationInfoServiceTest.java
- api/src/test/java/io/kafbat/ui/util/GithubReleaseInfoTest.java
Fixed https://github.com/kafbat/kafka-ui/issues/477.
> BE: Make gh version check timeout configurable

- frontend/src/components/common/Editor/Editor.tsx
> UX: Allow searching inside code textareas

- .github/workflows/docker_publish.yml
In the build push action use exact repo ECR name instead of output param from ecr login job.
> Infra: Fix ECR push action

- frontend/src/components/PageContainer/PageContainer.tsx
> FE: Fix unnecessary full page re-rendering

- .github/workflows/build-public-image.yml
Add ECR login via OIDC provider
> Infra: ECR Build minor fixes

- frontend/src/components/common/NewTable/Table.styled.ts
I added the CSS rule `white-space: pre;` to the table cell styling to ensure that ACLs with leading or trailing spaces are displayed correctly. This ensures that spaces are preserved in the UI, reflecting the actual data stored in Kafka.
> FE: Fix display of ACLs with leading/trailing spaces in table

- api/pom.xml
- api/src/test/java/io/kafbat/ui/serdes/PropertyResolverImplTest.java
- api/src/test/java/io/kafbat/ui/service/ksql/KsqlApiClientTest.java
- pom.xml
Bump several frameworks versions
- [?] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)
I don't know why yet, but make this `PropertyResolverImplTest` test pass, I needed to change the `CustomPropertiesClass` to a `record`! I'm still looking on this issue, though the functionality of mapping properties to custom classes is not used in the `kafka-ui` project.
I also had to change a little something in the `KsqlApiClientTest` test since Jackson now return DoubleNode instead of DecimalNode. Don't know why either. 
I let you decide if these differences are breaking changes.
Bump framework versions
- mapstruct : 1.5.5.Final -> 1.6.2
- lombok : 1.18.32 -> 1.18.34
- snakeyaml : 2.2 -> …
> BE: Chore: Bump Spring Boot w/ dependencies

- frontend/src/lib/hooks/filterUtils.ts
Simply chaned the default filter mode.
Hi, I’ve noticed that other users have also expressed a need for this change, and some of our Kafka users specifically mentioned it. I believe it’s a great idea to modify the default mode, as it aligns better with Kafka's real-time streaming nature.
**A picture of a cute animal (not …
> UX: Messages: Use "Newest" as default mode

- api/src/main/java/io/kafbat/ui/config/ReadOnlyModeFilter.java
- api/src/main/java/io/kafbat/ui/model/InternalBrokerConfig.java
- api/src/main/java/io/kafbat/ui/service/BrokerService.java
- frontend/src/components/Brokers/Broker/Configs/TableComponents/InputCell/InputCellViewMode.tsx
- frontend/src/components/Brokers/Broker/Configs/TableComponents/InputCell/styled.ts
There are some inconsistencies between the backend and frontend in the case of read-only clusters.
This results in enabled buttons which if you click them, get 405 error.
This PR tries to make them consistent.
* Make all configs of brokers read-only for read-only clusters
* Allow "analyze topic" for read-only clusters (https://github.com/provectus/kafka-ui/issues/1967), which seems to do no write-level action on the real data
There may be still some inconsistencies in the ACL page.
I can not check or fix them now, because I have no running kafka cluster with authentication/ACL enabled.
-  No need to
- Unit …
> Brokers: Improve accessibility for r/o clusters

- documentation/compose/e2e-tests.yaml
> Infra: Fix e2e compose

- .github/dependabot.yml
- api/Dockerfile
- Updated the docker build to use the latest JRE version. We should do our best to have reproducible builds(pinning to a sha instead of a tag) but we do not have any specific dependency on Java `17.0.11` 
- Updated the dependabot configuration to ensure that the docker image is updated automatically ignoring major upgrades (to avoid receiving a major Java upgrade as that will typically need more work)
Check out [Contributing](https://github.com/kafbat/kafka-ui/blob/main/.github/CONTRIBUTING.md) and [Code of …
> Chore: Deps: Use latest 17 jre image

- api/src/main/java/io/kafbat/ui/controller/MessagesController.java
According to `MessagesApi` the mode argument (Messages polling mode) is optional, so a null value is possible.
However, the `getTopicMessagesV2` method has a check for a non-null value for the mode argument.
The suggested solution is to set the default value to LATEST if mode is null.
**A picture of a cute animal (not …
> BE: Set default message polling mode

- frontend/src/components/Topics/Topic/Messages/Filters/AddEditFilterContainer.tsx
- frontend/src/components/Topics/Topic/Messages/Filters/Filters.styled.ts
- frontend/src/components/Topics/Topic/Messages/Filters/__tests__/AddEditFilterContainer.spec.tsx
Closes #622 
- Removed the check which was not rendering CEL help icon on edit filter. So the help icon is now visible for both add filter and edit filter.
- Added unit test for same icon to be visible and enabled in  both add and edit cases.
> FE: Filters: Display CEL help when editing filter

- api/src/main/java/io/kafbat/ui/config/auth/OAuthSecurityConfig.java
In the whole project only in one place `@Log4j2` is used, in other places `@Slf4j` is used.
Therefore, I suggest to use Slf4j logger everywhere.
> BE: Logger unification

- api/src/main/java/io/kafbat/ui/emitter/MessageFilters.java
- api/src/test/java/io/kafbat/ui/emitter/MessageFiltersTest.java
Closes https://github.com/kafbat/kafka-ui/issues/687
> BE: Messages: Allow searching in message headers

- .github/workflows/backend_tests.yml
- .github/workflows/branch-deploy.yml
- .github/workflows/build-public-image.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/cve_checks.yml
- .github/workflows/e2e-run.yml
- .github/workflows/main.yml
- .github/workflows/release-serde-api.yml
- .github/workflows/release.yml
- .github/workflows/separate_env_public_create.yml
- api/Dockerfile
- api/src/main/java/io/kafbat/ui/client/RetryingKafkaConnectClient.java
- api/src/main/java/io/kafbat/ui/service/ConsumerGroupService.java
- api/src/main/java/io/kafbat/ui/service/KafkaConnectService.java
- documentation/compose/connectors/start.sh
- documentation/compose/e2e-tests.yaml
- e2e-tests/pom.xml
- pom.xml
- serde-api/pom.xml
Resolves #490
bump java version to 21
- kafka client: 3.3.1 -> 3.8.0
- aspectj: 1.9.9.1 -> 1.9.21
Maven Plugins:
- clean: 3.2.0 -> 3.4.0
- compile: 3.10.1 -> 3.13.0
- resources: 3.2.0 -> 3.3.1
- surefire: 3.1.2 -> 3.5.1
- openapi generator : 6.6.0 -> 7.9.0
- springdoc openapi webflux: 1.2.32 -> 1.8.0
- surefire: 3.2.3 -> 3.5.1 (for e2e tests)
- surefire-ng: 3.2.5 -> 3.5.1 (for e2e tests)
Check out [Contributing](https://github.com/kafbat/kafka-ui/blob/main/.github/CONTRIBUTING.md) and [Code of …
> BE: Chore: Upgrade java to 21

- api/src/test/java/io/kafbat/ui/KafkaConnectServiceTests.java
- api/src/test/java/io/kafbat/ui/KafkaConsumerTests.java
- api/src/test/java/io/kafbat/ui/config/auth/azure/AzureEntraLoginCallbackHandlerTest.java
- api/src/test/java/io/kafbat/ui/config/auth/azure/AzureEntraOAuthBearerTokenTest.java
- api/src/test/java/io/kafbat/ui/container/KafkaConnectContainer.java
- api/src/test/java/io/kafbat/ui/container/KsqlDbContainer.java
- api/src/test/java/io/kafbat/ui/container/SchemaRegistryContainer.java
- api/src/test/java/io/kafbat/ui/emitter/CursorTest.java
- api/src/test/java/io/kafbat/ui/emitter/TailingEmitterTest.java
- api/src/test/java/io/kafbat/ui/serdes/SerdesInitializerTest.java
- api/src/test/java/io/kafbat/ui/serdes/builtin/ConsumerOffsetsSerdeTest.java
- api/src/test/java/io/kafbat/ui/serdes/builtin/ProtobufFileSerdeTest.java
- api/src/test/java/io/kafbat/ui/service/BrokerServiceTest.java
- api/src/test/java/io/kafbat/ui/service/ConfigTest.java
- api/src/test/java/io/kafbat/ui/service/LogDirsTest.java
- api/src/test/java/io/kafbat/ui/service/MessagesServiceTest.java
- api/src/test/java/io/kafbat/ui/service/OffsetsResetServiceTest.java
- api/src/test/java/io/kafbat/ui/service/ReactiveAdminClientTest.java
- api/src/test/java/io/kafbat/ui/service/SchemaRegistryPaginationTest.java
- api/src/test/java/io/kafbat/ui/service/SendAndReadTests.java
- api/src/test/java/io/kafbat/ui/service/acl/AclsServiceTest.java
- api/src/test/java/io/kafbat/ui/service/analyze/TopicAnalysisServiceTest.java
- api/src/test/java/io/kafbat/ui/service/integration/odd/ConnectorsExporterTest.java
- api/src/test/java/io/kafbat/ui/service/integration/odd/SchemaReferencesResolverTest.java
- api/src/test/java/io/kafbat/ui/service/integration/odd/TopicsExporterTest.java
- api/src/test/java/io/kafbat/ui/service/quota/ClientQuotaServiceTest.java
- api/src/test/java/io/kafbat/ui/util/jsonschema/JsonAvroConversionTest.java
A small cleanup in the api module tests.
Fixed IDEA warnings, removed unused imports, etc.
> BE: Chore: Cleanup api tests

- api/src/main/java/io/kafbat/ui/client/RetryingKafkaConnectClient.java
- api/src/test/java/io/kafbat/ui/KafkaConnectServiceTests.java
- etc/checkstyle/checkstyle.xml
Closes https://github.com/kafbat/kafka-ui/issues/681
Example: 
> BE: KC: Expose Kafka Connect validation errors in the UI

- api/src/main/java/io/kafbat/ui/service/KafkaConnectService.java
A small change to take advantage of newer language features
> BE: Chore: use enhanced switch

- .github/workflows/frontend_tests.yml
- frontend/package.json
- pom.xml
Upgrades pnpm to the latest version(9.15.0)
Besides the expected upstream patches in pnpm , it also unblocks dependabot upgrades 
See https://github.com/dependabot/dependabot-core/issues/11124
> Infra: FE: Bump pnpm to 9.15.0

- .dev/dev_arm64.yaml
- .gitignore
- api/pom.xml
- api/src/main/java/io/kafbat/ui/client/RetryingKafkaConnectClient.java
- api/src/test/java/io/kafbat/ui/AbstractIntegrationTest.java
- documentation/compose/e2e-tests.yaml
- e2e-tests/pom.xml
- e2e-tests/src/main/java/io/kafbat/ui/screens/panels/NaviSideBar.java
- e2e-tests/src/main/java/io/kafbat/ui/screens/topics/TopicSettingsTab.java
- pom.xml
**Description** 
Before this change, we were using both Confluent Artifacts (via `confluent.version`) as well as the OSS artifacts (via `kafka-clients.version` and `kafka.version` ).
With this change, we are upgrading and aligning the versions to use the Confluent Kafka Distribution. This helps us not only to reduce the attack surface but also to simplify the dependency upgrades
As a side effect of this upgrade, we are also extending the retry logic to retry when there is a re-balance in progress as that was previously failing silently as described in https://issues.apache.org/jira/browse/KAFKA-14455
Closes https://github.com/kafbat/kafka-ui/pull/693
Closes https://github.com/kafbat/kafka-ui/pull/692 …
> BE: Chore: Upgrade kafka to confluent 7.8.0

- api/src/main/java/io/kafbat/ui/serdes/builtin/ProtobufFileSerde.java
Before this change, the `SchemaRegistryServiceTests` tests were failing in Windows with the following exception: 
```java
at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:782)
... 55 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.kafbat.ui.service.DeserializationService]: Constructor threw exception
at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:221)
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:315)
... 69 more
Caused by: …
```
> BE: Chore: standarize Protobuf import paths

- api/src/main/java/io/kafbat/ui/model/rbac/AccessContext.java
Fixed https://github.com/kafbat/kafka-ui/issues/253
> BE: RBAC: Ignore values for non-applicable resources

- .github/workflows/cve_checks.yml
- .github/workflows/infra_discord_hook.yml
> Infra: Discord hook for failed CVE runs

- frontend/src/components/ConsumerGroups/List.tsx
- frontend/src/components/ConsumerGroups/__test__/List.spec.tsx
> Reasons for setting up Git incorrectly
> https://github.com/kafbat/kafka-ui/pull/686
> created a new PR with the same content as the PR above.
close #675 
The default value of Consumer Lag displayed when searching the Consumer List has been modified.
The existing displayed value is 'N/A', which is different from the response value of '0' that the server responds to.
We believe that 'N/A' may mean a state of disuse, so we write it as 0 to make it clear.
What changes did you make? (Give an overview)
Is there anything you'd like reviewers to focus on?
How Has This Been Tested? (put an "x" (case-sensitive!) next to an item)
**How Has This Been Tested?** (put an "x" (case-sensitive!) …
> FE: Consumers: Fix lag is displayed as 'N/A' in case of null value

- api/src/main/java/io/kafbat/ui/util/StaticFileWebFilter.java
> BE: Auth: Fix startup error on missing index

- documentation/compose/auth-context.yaml
- documentation/compose/cluster-sr-auth.yaml
- documentation/compose/kafbat-ui.yaml
- documentation/compose/kafka-ssl-components.yaml
- documentation/compose/kafka-ssl.yml
- documentation/compose/kafka-zookeeper.yaml
- documentation/compose/ui-acl-with-zk.yaml
- documentation/compose/ui-connectors-auth.yaml
- documentation/compose/ui-jmx-secured.yml
- documentation/compose/ui-ldap.yaml
- documentation/compose/ui-sasl.yaml
- documentation/compose/ui-serdes.yaml
- documentation/compose/ui-with-jmx-exporter.yaml
This is a an accidental documentation miss from https://github.com/kafbat/kafka-ui/pull/710
> Docs: Update confluent version in the examples

- .dev/dev.yaml
- documentation/compose/DOCKER_COMPOSE.md
This should not be needed. See https://github.com/kafbat/kafka-ui/pull/704
This pull request is accompanied by the following doc update https://github.com/kafbat/ui-docs/pull/35
> Docs: Remove references to arm-specific local setup

- .github/workflows/cve_checks.yml
Closes https://github.com/kafbat/kafka-ui/issues/707
Tested here : 
- `main` : https://github.com/yeikel/kafka-ui/actions/runs/12602983150/job/35127088622
- Pull request: https://github.com/yeikel/kafka-ui/actions/runs/12603014749/job/35127194824?pr=68
> Infra: Run cve checks workflow on pull requests and pushes to main

- frontend/package.json
This change is a follow up for https://github.com/kafbat/kafka-ui/pull/747 to only enforce the major versions. 
Minor and feature revision enforcement is not necessary and adds little value.  
A sample situations where this can hurt us include Dependabot and other tools. 
> Infra: FE: limit pnpm and node version enforcement to the major versions

- .github/workflows/docker_publish.yml
Ref: #242
Improve publishig to Public AWS ECR by trimming repo owner from repo name so that Public ERC repo url has no duplcates.
Before: `public.ecr.aws/kafbat/kafbat/kafka-ui`
After: `public.ecr.aws/kafbat/kafka-ui`
> Infra: Adjust publish action for AWS ECR

- .dev/dev.yaml
- documentation/compose/auth-context.yaml
- documentation/compose/cluster-sr-auth.yaml
- documentation/compose/e2e-tests.yaml
- documentation/compose/kafbat-ui.yaml
- documentation/compose/kafka-ssl-components.yaml
- documentation/compose/kafka-ssl.yml
- documentation/compose/ui-acl-with-zk.yaml
- documentation/compose/ui-connectors-auth.yaml
- documentation/compose/ui-jmx-secured.yml
- documentation/compose/ui-ldap.yaml
- documentation/compose/ui-sasl.yaml
- documentation/compose/ui-serdes.yaml
- documentation/compose/ui-with-jmx-exporter.yaml
Close https://github.com/kafbat/kafka-ui/issues/795
> Docs: Fix broken composes

- frontend/src/components/Topics/Topic/Messages/MessagesTable.tsx
- frontend/src/components/Topics/Topic/Messages/__test__/MessagesTable.spec.tsx
- frontend/src/lib/hooks/useLocalStorage.ts
> FE: Topics: Save field previews into local storage

- api/pom.xml
- api/src/main/java/io/kafbat/ui/config/auth/LdapSecurityConfig.java
- api/src/main/java/io/kafbat/ui/util/CustomSslSocketFactory.java
- api/src/test/java/io/kafbat/ui/AbstractActiveDirectoryIntegrationTest.java
- api/src/test/java/io/kafbat/ui/ActiveDirectoryLdapTest.java
- api/src/test/java/io/kafbat/ui/ActiveDirectoryLdapsTest.java
- api/src/test/java/io/kafbat/ui/container/ActiveDirectoryContainer.java
In this PR I added `CustomSslSocketFactory` that trusts all certificates by default. 
This allows you to use LDAPS to connect to an AD server without further specifying the path to the truststore/password.
> BE: Auth: Support LDAPS for AD

- README.md
> Docs: Get back AMI link

- api/src/main/java/io/kafbat/ui/config/GeneralSecurityConfig.java
Some questionable decisions on spring's side resulted in us unable to receive HTTP requests with encoded forward slash
https://github.com/spring-projects/spring-security/commit/0e257b56ce35402558a260ffa6b368982f9a7934#diff-497e4c636b38384ac7f55614db8d7613dfbd02b77b0287c1954f9e7fc42e72c0R64-R67
https://github.com/spring-projects/spring-security/issues/15967
Resolves #848
Check out [Contributing](https://github.com/kafbat/kafka-ui/blob/main/.github/CONTRIBUTING.md) and [Code of …
> BE: SR: Fix HTTP 400 with slashes in schema name

- pom.xml
How Has This Been Tested? (put an "x" (case-sensitive!) next to an item)
> * [x]  Covered by existing automation
Fix CVE-2024-57699. See https://github.com/kafbat/kafka-ui/actions/runs/13409810358/job/37457162824
> BE: overwrite json-smart

- api/src/main/java/io/kafbat/ui/service/AdminClientServiceImpl.java
> Fix supply AdminClient creation

- api/src/main/java/io/kafbat/ui/config/ClustersProperties.java
- api/src/main/java/io/kafbat/ui/model/KafkaCluster.java
- api/src/main/java/io/kafbat/ui/service/ConsumerGroupService.java
- api/src/main/java/io/kafbat/ui/service/KafkaClusterFactory.java
- api/src/main/java/io/kafbat/ui/service/MessagesService.java
- api/src/test/java/io/kafbat/ui/AbstractIntegrationTest.java
- api/src/test/java/io/kafbat/ui/service/ConfigTest.java
Resolves https://github.com/kafbat/kafka-ui/issues/527
> BE: Allow overriding producer and consumer properties

- .github/workflows/backend_tests.yml
- .github/workflows/frontend_tests.yml
- api/build.gradle
- gradle/libs.versions.toml
> BE: Fix deps and build

- frontend/src/widgets/ClusterConfigForm/ClusterConfigForm.styled.ts
- frontend/src/widgets/ClusterConfigForm/Sections/Serdes.tsx
- frontend/src/widgets/ClusterConfigForm/Sections/Serdes/PropertiesFields.tsx
- frontend/src/widgets/ClusterConfigForm/Sections/Serdes/Serdes.tsx
- frontend/src/widgets/ClusterConfigForm/index.tsx
- frontend/src/widgets/ClusterConfigForm/schema.ts
- frontend/src/widgets/ClusterConfigForm/types.ts
- frontend/src/widgets/ClusterConfigForm/utils/getInitialFormData.ts
- frontend/src/widgets/ClusterConfigForm/utils/transformFormDataToPayload.ts
> Wizard: Support Editing serdes

- gradle/libs.versions.toml
https://spring.io/blog/2025/03/20/spring-boot-3-4-4-available-now 
It should fix CVE-2025-22228
> BE: Chore: Bump Spring Boot to 3.4.4

- .github/workflows/backend_tests.yml
- .github/workflows/block_merge.yml
- .github/workflows/branch-deploy.yml
- .github/workflows/branch-remove.yml
- .github/workflows/build-public-image.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/cve_checks.yml
- .github/workflows/delete-public-image.yml
- .github/workflows/docker_build.yml
- .github/workflows/docker_publish.yml
- .github/workflows/e2e-run.yml
- .github/workflows/frontend_tests.yml
- .github/workflows/infra_discord_hook.yml
- .github/workflows/main.yml
- .github/workflows/md-links.yml
- .github/workflows/pr_linter.yml
- .github/workflows/release-serde-api.yml
- .github/workflows/release.yml
- .github/workflows/release_drafter.yml
- .github/workflows/separate_env_public_create.yml
- .github/workflows/welcome-first-time-contributors.yml
- .github/workflows/workflow_linter.yml
fixes #921 
details :
```
uses: actions/checkout@v4
```
to 
```
uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2
```
```
uses: actions/setup-java@v4
```
to
```
uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12
```
```
uses: actions/cache@v4
```
to
```
uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf
```
```
uses: actions/download-artifact@v4
```
to
```
uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806
```
```
uses: actions/upload-artifact@v4
```
to
```
uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1
```
```
uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502  # infered from @v4
```
```
uses: aws-actions/amazon-ecr-login@9238dd443b7a5941caf19ffbe68be34d4dbd61df # …
```
> Update: GitHub Actions workflows to use specific versions of actions

- frontend/src/components/Topics/Topic/Messages/MessageContent/MessageContent.tsx
We currently only format JSON objects, but we can detect and format JSON arrays as well, which will improve the user experience when messages contain arrays of JSON objects.
Before:
After:
**What changes did you make?**
Changed JSON message detection to include messages starting with `[`, not only `{`.
No.
**How Has This Been Tested?**
**Checklist**
**A picture of a cute animal**
> FE: Messages: Format JSON arrays

- api/src/main/java/io/kafbat/ui/service/KafkaConfigSanitizer.java
- api/src/test/java/io/kafbat/ui/service/KafkaConfigSanitizerTest.java
**What changes did you make?** Add "passphrase" as a default pattern to sanitize in the configs.
> BE: Extend config sanitizer patterns

- e2e-tests/src/main/java/io/kafbat/ui/screens/brokers/BrokersList.java
- frontend/src/components/Brokers/BrokersList/SkewHeader/SkewHeader.tsx
- frontend/src/components/Brokers/BrokersList/TableCells/TableCells.tsx
- frontend/src/components/Brokers/BrokersList/lib/types.ts
- frontend/src/components/Brokers/BrokersList/lib/utils.ts
Resolves #526.
The value shown in the `Online Partitions` column of the brokers list table was modified in #137. This PR restores the original logic used to render `Online Partitions` prior to #137.
> FE: Fix 'Online Partitions' column

- gradle/libs.versions.toml
> BE: Chore: Bump Spring Boot to 3.4.5

- api/build.gradle
- frontend/src/lib/constants.ts
- frontend/src/widgets/ClusterConfigForm/schema.ts
- frontend/src/widgets/ClusterConfigForm/utils/getJaasConfig.ts
- frontend/src/widgets/ClusterConfigForm/utils/transformFormDataToPayload.ts
- gradle/libs.versions.toml
resolves #1012
The front end especially.
> BE: Auth: Support GCP IAM Auth

- api/src/main/java/io/kafbat/ui/service/ReactiveAdminClient.java
- api/src/main/java/io/kafbat/ui/util/MetadataVersion.java
> BE: Internal: Support version getter from `metadata.version`

- api/src/main/java/io/kafbat/ui/serdes/ConsumerRecordDeserializer.java
- api/src/main/java/io/kafbat/ui/util/ContentUtils.java
- api/src/test/java/io/kafbat/ui/util/ContentUtilsTest.java
> BE: Messages: Format non-string headers

- api/src/main/java/io/kafbat/ui/service/TopicsService.java
> BE: Exclude offline nodes from target calculation when adjusting the replication factor

- frontend/src/widgets/ClusterConfigForm/Sections/Authentication/AuthenticationMethods.tsx
- frontend/src/widgets/ClusterConfigForm/schema.ts
- frontend/src/widgets/ClusterConfigForm/utils/transformFormDataToPayload.ts
Added support for the optional `awsRoleArn` configuration when using IAM authentication.
In addition to `awsRoleArn`, I have also added `awsRoleSessionName` & `awsStsRegion` as defined here in [MSK IAM Auth Library](https://github.com/aws/aws-msk-iam-auth?tab=readme-ov-file#specifying-an-aws-iam-role-for-a-client).
```
sasl.jaas.config=software.amazon.msk.auth.iam.IAMLoginModule required awsRoleArn="arn:aws:iam::123456789012:role/msk_client_role" awsRoleSessionName="producer"  awsStsRegion="us-west-2";
```
Docs PR: https://github.com/kafbat/ui-docs/pull/61
**Checklist** (put an "x" (case-sensitive!) next to …
> FE: Support `awsRoleArn` when using IAM Auth

- frontend/src/components/ACLPage/List/List.tsx
- frontend/src/components/Brokers/BrokersList/lib/utils.ts
- frontend/src/components/Connect/List/List.tsx
- frontend/src/components/ConsumerGroups/List.tsx
- frontend/src/components/Dashboard/ClusterName.tsx
- frontend/src/components/Dashboard/Dashboard.tsx
- frontend/src/components/KsqlDb/TableView.tsx
- frontend/src/components/NavBar/NavBar.styled.ts
- frontend/src/components/Schemas/List/List.tsx
- frontend/src/components/Topics/List/TopicTable.tsx
- frontend/src/components/Topics/List/TopicTitleCell.tsx
- frontend/src/components/common/NewTable/BreakableTextCell.tsx
- frontend/src/components/common/NewTable/LinkCell.tsx
- frontend/src/components/common/NewTable/Table.styled.ts
- frontend/src/theme/theme.ts
Added new shared component  BreakableTextCell that allows to break the text of table column by separators or by letter
Set column width for some table ( Dashboards, Brokers, Topics etc)
Fixed main header transparency bug
> Issue_528_style_table_column_width

- api/build.gradle
- gradle/libs.versions.toml
**What changes did you make? (Give an overview)**
- Upgraded Spring Boot to the latest version (`3.5.3`) to fetch the latest bug fixes and features as well as fixing CVE-2025-41234 
- Removed several dependency overrides that are no longer necessary since they were upgraded by Spring
- Removed the explicit inclusion of `Junit5` , as it is provided transitively by `spring-boot-starter-test`. Keeping it explicitly declared leads to version conflicts, which goes against the [JUnit project's recommendations for Spring Boot](https://docs.junit.org/snapshot/user-guide/#running-tests-build-spring-boot).
**A picture of a …
> BE: Chore: Bump Spring Boot to 3.5.3

- .github/CODEOWNERS
- .github/dependabot.yml
The `reviewers` field in the `dependabot.yml` file will be removed soon. For more information, see [this blog post](https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/).
This pull request removes the usage of the `reviewers` field and creates a `CODEWNERS` file instead
> Infra: Replace usage of Dependabot's reviewers with CODEOWNERS

- .github/dependabot.yml
While Dependabot's grouped updates can be convenient, they should be used with care, particularly in projects with a large number of dependencies like this one. 
Grouped updates often combine changes that are not compatible with each other, which can make upgrades more difficult and increase the risk of breaking the build. For instance, https://github.com/kafbat/kafka-ui/pull/1163 includes over 20 updates, and it's not surprising that the build is currently failing. Reviewing and validating that many changes at once is a significant challenge.
This pull request takes an initial step toward organizing updates into smaller, more focused groups, beginning with Spring . Spring was selected because it is both a common source of security advisories and a foundational component of the project’s …
> Infra: Create dedicated Dependabot group for Spring dependencies

- README.md
> Docs: Updated feature list

- contract/build.gradle
- contract/src/main/resources/swagger/kafbat-ui-api.yaml
- gradle/libs.versions.toml
> BE: Contracts: Enable openapi contracts validator

- .github/dependabot.yml
It looks like Dependabot doesn’t handle this by default. With the current configuration, it still assigns the Spring dependencies to the default group instead of the dedicated Spring Boot group.
See https://github.com/kafbat/kafka-ui/pull/1271 for an example
This a follow up for https://github.com/kafbat/kafka-ui/pull/1181
> Infra: Exclude Springboot dependencies from the `other-dependencies` dependabot group

- frontend/src/components/ConsumerGroups/List.tsx
- frontend/src/components/Topics/List/TopicTable.tsx
> FE: Manual column width for Consumers and Topics tables

- .github/dependabot.yml
Follow up for https://github.com/kafbat/kafka-ui/pull/1323
Although the previous configuration was technically accurate regarding the groups, it resulted in Netty upgrades being processed individually rather than grouped. This update ensures Netty upgrades are fully ignored, as originally intended.
Closes https://github.com/kafbat/kafka-ui/pull/1326
> Infra: Ignore Netty updates

- frontend/src/components/Schemas/List/List.tsx
> FE: Fixed schema sort

- documentation/compose/DOCKER_COMPOSE.md
Removed duplicate entry for kafka-ui.yaml and adjusted numbering.
> Fix duplicate entry in docker-compose documentation

- frontend/src/components/Nav/Menu/styled.ts
> FE: Reduce nav bar height
