kafbat/kafka-ui

api/src/main/java/io/kafbat/ui/model/rbac/Resource.java

RBAC: Fix 403 when viewing audit topic messages

---

api/src/main/java/io/kafbat/ui/service/KafkaConfigSanitizer.java
api/src/test/java/io/kafbat/ui/service/KafkaConfigSanitizerTest.java

Check out [Contributing](https://github.com/provectus/kafka-ui/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/provectus/kafka-ui/blob/master/CODE-OF-CONDUCT.md)

BE: Sanitize connection.uri for mongo

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/components/App.tsx

I've added React Query devtool for better debugging experience.

FE: Chore: Add React Query Devtool

---

api/pom.xml

BE: Bump aws-msk-iam-auth dependency

---

frontend/package.json
frontend/pnpm-lock.yaml

FE: Bump misc dependencies

---

.github/workflows/backend_tests.yml
.github/workflows/branch-deploy.yml
.github/workflows/build-public-image.yml
.github/workflows/codeql-analysis.yml
.github/workflows/cve.yml
.github/workflows/frontend_tests.yml
.github/workflows/main.yml
.github/workflows/release-serde-api.yml
.github/workflows/release.yml
.github/workflows/release_drafter.yml
.github/workflows/separate_env_public_create.yml

Infra: Bump dependencies

---

documentation/compose/kafbat-ui.yaml

Resolves #377
BROKER_ID should be unique, so i modified `KAFKA_BROKER_ID` of kafka1 to `2`, and accordingly, i also modified `KAFKA_JMX_OPTS`, `KAFKA_NODE_ID`, and `KAFKA_CONTROLLER_QUORUM_VOTERS`

Docs: Make broker id values unique

---

api/src/main/java/io/kafbat/ui/util/GithubReleaseInfo.java

BE: Increase gh call timeout

---

api/src/main/java/io/kafbat/ui/serdes/builtin/ProtobufFileSerde.java

Follow symlinks in proto files lookup

---

contract/src/main/resources/swagger/kafbat-ui-api.yaml
contract/src/main/resources/swagger/kafka-connect-api.yaml

BE: Add Restarting connector state enum

---

.github/workflows/frontend_tests.yml
frontend/README.md
frontend/package.json
frontend/pnpm-lock.yaml
pom.xml

FE: Update pnpm version

---

frontend/src/components/Connect/Details/Actions/Actions.tsx
frontend/src/components/Connect/Details/Tasks/ActionsCellTasks.tsx
frontend/src/components/Connect/List/ActionsCell.tsx

FE: RBAC: Fix connector permissions checks

---

frontend/src/components/Topics/Topic/Messages/MessagesTable.tsx
frontend/src/components/Topics/Topic/Messages/__test__/MessagesTable.spec.tsx
frontend/src/lib/hooks/api/topicMessages.tsx
frontend/src/lib/hooks/useMessagesFilters.ts

FE: Messages: Fix refresh does pagination instead

---

frontend/src/components/ACLPage/Form/ForProducers/lib.ts
frontend/src/components/ACLPage/Form/ForProducers/types.ts

**What changes did you make?** 
I changed two files that contained typos.
Fixes #424
**Is there anything you'd like reviewers to focus on?** 
It's a small PR I don't think there's much to review :)
- [X ] No need to
- [X ] I have performed a self-review of my own code
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [ X] My changes generate no new warnings (e.g. Sonar is happy)
- [ X] I have added tests that prove my fix is effective or that my feature works
- [ X] New and existing unit tests pass …

FE: ACL: Fix Idempotent_write ACL is not created

---

documentation/compose/ui-acl-with-zk.yaml

Just a small change that allowed me to run the docker compose file while developing. I got this error when running `docker compose`
ui-acl-with-zk.yaml: `version` is obsolete
- [ X] Manually (please, describe, if necessary)
- [ X] I have performed a self-review of my own code
- [ X] I have commented my code, particularly in hard-to-understand areas
- [X ] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [X ] My changes generate no new warnings (e.g. Sonar is happy)
- [X ] …

Docs: Update zookeeper image

---

.github/workflows/e2e-run.yml

Infra: Fix e2e compose run

---

.github/workflows/frontend_tests.yml
frontend/package.json
pom.xml

Infra: FE: Bump pnpm

---

.github/workflows/docker_publish.yml

Fix env reference in the image build/push workflow. The ECR_REGISTRY Configuration variable configured on repo level.

Infra: Fix ECR push action

---

api/pom.xml

Chore: Deps: Bump aws sdk

---

api/src/main/java/io/kafbat/ui/service/rbac/AccessControlService.java

BE: Wizard: Fix nullable cluster perms check

---

api/src/main/java/io/kafbat/ui/model/rbac/Role.java

BE: RBAC: Add cluster list validation

---

README.md

The quick start link is broken.

---

frontend/src/components/common/NewTable/Table.styled.ts

UX: SR: Adjust subjects name list max width

---

frontend/package.json

See https://github.com/dependabot/dependabot-core/issues/11124
```
git checkout 394f2ca073b05531f199a3c964cc231fe2212446
pnpm --version                     
9.15.1
>pnpm install    
Lockfile is up to date, resolution step is skipped
Already up to date
Done in 1.7s
```

Infra: FE: Enforce pnpm using a range

---

api/src/main/java/io/kafbat/ui/config/auth/LdapSecurityConfig.java

LDAP: Fix property nullability condition

---

contract/src/main/resources/swagger/kafka-sr-api.yaml
e2e-tests/src/test/java/io/kafbat/ui/smokesuite/brokers/BrokersTest.java

SR: Fix config path

---

pom.xml

I've upgrading Spring boot to 3.4.2
Upgrading the dependencies too to follow the Spring Boot dependencies : 
- assertj from 3.25.3 to 3.26.3
- jackson from 2.14.0 to 2.18.2
- junit from 5.11.2 to 5.11.4
Though the build and local tests are ok, but the jackson bump seems big, maybe the could be issues.
**A picture of a cute …

BE: Chore: Upgrade spring boot to 3.4.2

---

api/build.gradle

BE: Fix spring boot build info population

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/components/Topics/Topic/SendMessage/__test__/utils.spec.ts
frontend/src/components/Topics/Topic/SendMessage/utils.ts

Migrate https://github.com/provectus/kafka-ui/pull/4390 by @philosomniac
Resolve https://github.com/kafbat/kafka-ui/issues/898

FE: Messages: Add schema validation support for more json-schema version refs

---

api/src/main/java/io/kafbat/ui/model/rbac/Role.java

- Fixed issues with rbac rules validations

BE: RBAC: Fix RBAC rules validations

---

.github/dependabot.yml

Infra: Group dependabot updates

---

frontend/src/components/NavBar/UserInfo/UserInfo.styled.ts
frontend/src/components/NavBar/UserInfo/UserInfo.tsx
frontend/src/components/common/Dropdown/DropdownItem.tsx

UX: Auth: Logout button is inaccessible

---

README.md

Added Powered by JetBrains

---

README.md

docs: use syntax highlighting

---

api/src/main/java/io/kafbat/ui/config/auth/LdapProperties.java
api/src/main/java/io/kafbat/ui/config/auth/LdapSecurityConfig.java

BE: Auth: Fix LDAP SPEL

---

api/src/test/java/io/kafbat/ui/service/rbac/MockedRbacUtils.java
api/src/test/java/io/kafbat/ui/service/rbac/RbacClusterMistakenTest.java
api/src/test/java/io/kafbat/ui/service/rbac/RbacEditTopicTest.java
api/src/test/java/io/kafbat/ui/service/rbac/RbacTopicCreationTest.java

BE: Fix build

---

api/src/main/java/io/kafbat/ui/emitter/MessageFilters.java
api/src/test/java/io/kafbat/ui/emitter/MessageFiltersTest.java

BE: Messages: Implement null filtering for CEL

---

frontend/src/widgets/ClusterConfigForm/schema.ts

Added missing enums. Fixes #1012

FE: Auth: Add GCP IAM missing enums

---

api/build.gradle
gradle/libs.versions.toml

BE: Patch CVEs

---

frontend/src/components/ConsumerGroups/Details/ResetOffsets/Form.tsx

Redirect to consumer group page after offset reset

---

gradle/libs.versions.toml

Bumps Apache Commons-lang3 from 3.12.0 to 3.18.0 and fixes [CVE-2025-48924](https://github.com/advisories/GHSA-j288-q9x7-2f5v)

BE: Chore: Bump Apache Commons-lang3 from 3.12.0 to 3.18.0

---

api/build.gradle
gradle/libs.versions.toml

BE: Chore: Overwrite nimbus-jose-jwt temporarily to fix CVE-2025-5386

---

api/build.gradle
gradle/libs.versions.toml

A small follow up for https://github.com/kafbat/kafka-ui/pull/1180 to fix a typo in the documentation and avoid confusions 
The vulnerability is CVE-2025-53864 not CVE-2025-5386

BE: Chore:  Fix documentation typo

---

frontend/src/components/Brokers/Broker/Configs/TableComponents/InputCell/InputCellViewMode.tsx
frontend/src/components/common/ActionComponent/ActionButton/ActionCanButton/ActionCanButton.tsx

FE: RBAC problem for broker settings

---

e2e-playwright/src/features/TopicsMessages.feature
e2e-playwright/src/pages/Topics/TopicsTopickNameLocators.ts
e2e-playwright/src/steps/ProduceMessages.ts

E2E Playwright: Topic message menu fix

---

frontend/src/lib/hooks/useTimezones.ts

FE: Add Plain UTC timezone

---

api/src/main/java/io/kafbat/ui/serdes/builtin/ProtobufFileSerde.java

Corrected text in error message.
Confirm code against message.
Häh?!?!

Chore: Fix grammar

---

frontend/src/components/Topics/Topic/Messages/Message.tsx
frontend/src/components/Topics/Topic/Messages/MessageContent/MessageContent.tsx
frontend/src/components/Topics/Topic/Messages/__test__/Message.spec.tsx
frontend/src/lib/dateTimeHelpers.ts

FE: Don't omit milliseconds in timestamps

---

frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/components/Topics/Topic/Messages/Filters/__tests__/Filters.spec.tsx

FE: Some CVE fixes

---

api/src/main/java/io/kafbat/ui/controller/SchemasController.java

Fixed nulls sorting

---

frontend/src/components/Nav/ClusterMenu/ClusterMenu.tsx

Open cluster menu if cluster name in url changed

---

api/src/main/java/io/kafbat/ui/service/ConsumerGroupService.java
api/src/main/java/io/kafbat/ui/service/KafkaConnectService.java
api/src/main/java/io/kafbat/ui/service/index/NgramFilter.java
api/src/main/java/io/kafbat/ui/service/index/SchemasFilter.java
api/src/test/java/io/kafbat/ui/service/index/AbstractNgramFilterTest.java
api/src/test/java/io/kafbat/ui/service/index/AclBindingFilterTest.java
api/src/test/java/io/kafbat/ui/service/index/ConsumerGroupFilterTest.java
api/src/test/java/io/kafbat/ui/service/index/KafkaConnectNgramFilterTest.java
api/src/test/java/io/kafbat/ui/service/index/SchemasFilterTest.java

BE: Fixed filter comparators

---

api/Dockerfile

BE: Fix alpine CVEs
